CREATE TABLE IF NOT EXISTS users_table (
    user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(64) NOT NULL UNIQUE,
    email varchar(255) NOT NULL UNIQUE,
    hashed_password varchar(255) NOT NULL
);